name: volren-atlas
channels: !!python/tuple
- !!python/unicode 'defaults'
dependencies:
- backports=1.0=py27_0
- backports_abc=0.4=py27_0
- bokeh=0.12.3=py27_0
- chest=0.2.3=py27_0
- cloudpickle=0.2.1=py27_0
- dask=0.11.1=py27_0
- freetype=2.5.5=1
- futures=3.0.5=py27_0
- h5py=2.6.0=np111py27_2
- hdf5=1.8.17=1
- heapdict=1.0.0=py27_1
- jinja2=2.8=py27_1
- jpeg=8d=2
- lcms=1.19=0
- libgfortran=3.0.0=1
- libpng=1.6.22=0
- locket=0.2.0=py27_1
- markupsafe=0.23=py27_2
- mkl=11.3.3=0
- numpy=1.11.2=py27_0
- openssl=1.0.2j=0
- pandas=0.19.0=np111py27_0
- partd=0.3.6=py27_0
- pil=1.1.7=py27_2
- pip=8.1.2=py27_0
- python=2.7.12=1
- python-dateutil=2.5.3=py27_0
- pytz=2016.7=py27_0
- pyyaml=3.12=py27_0
- readline=6.2=2
- requests=2.11.1=py27_0
- scipy=0.18.1=np111py27_0
- setuptools=27.2.0=py27_0
- singledispatch=3.4.0.3=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- ssl_match_hostname=3.4.0.2=py27_1
- tk=8.5.18=0
- toolz=0.8.0=py27_0
- tornado=4.4.2=py27_0
- wheel=0.29.0=py27_0
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - backports-abc==0.4
  - backports.ssl-match-hostname==3.4.0.2
  - pydicom==0.9.9
  - pynrrd==0.2.1

